-- 2026-07-27: subscription expiry fallback fix landed (internal/service/payment.go
-- resolveSubExpiry helper). Pre-existing rows with expires_at IS NULL were
-- activated without a sub_expires_at hint, so the auth path treats them as
-- "never expires" (isExpiredAt: NULL means never expires).
--
-- Decision: do NOT backfill. Two reasons:
--   1. started_at is also written at activation time. For pre-fix rows,
--      started_at is real (e.g. 6 months ago). Issuing a fresh
--      now() + interval_days would silently give a paying customer a
--      longer subscription than they paid for.
--   2. started_at + interval_days is already in the past for any
--      pre-fix row except the most recent activations, so backfilling
--      with that formula would immediately mark them expired.
--
-- Resolution mechanism: any subsequent activation (renewal confirm,
-- webhook re-delivery) goes through the new resolveSubExpiry helper and
-- writes a fresh now() + interval_days. Manual remediation for stuck
-- accounts is via DELETE /user/subscriptions/:id + re-purchase.
--
-- This is a no-op migration deliberately — it documents the decision in
-- the same file so the choice is traceable.
SELECT 1;
